blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/spanio/SPAN-API-Client-Docs/discussions
    about: Questions about SPAN API usage, feature requests, sharing projects, and community discussion
